import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:flutter/services.dart' show rootBundle;

import '../../models/models.dart';
import '../drift/app_database.dart';
import 'cocktail_image_assets.dart';
import 'cocktail_tags.dart';
import 'recipe_drift_seed.dart';

/// Bundled expansion pack from `cocktails_import.json`, processed to:
/// single-glass servings, metric (ml/dash), accurate descriptions, and garnishes.
///
/// Regenerated by `tool/generate_cocktails_import_seed.py`.
const cocktailsImportSeedAsset = 'assets/seed/cocktails_import_seed.json';

/// Prefix for every import-pack cocktail id (`cocktail_imp_...`).
const cocktailsImportIdPrefix = 'cocktail_imp_';

/// Seeds the cocktails import expansion pack when it is not already present.
///
/// Safe on every startup: if any `cocktail_imp_*` recipe exists, this is a
/// **no-op** so favourites and other user state on those rows are preserved.
/// Fresh install / factory reset wipes the table and re-seeds via [seedRecipes].
Future<void> seedCocktailsImport(String defaultBoatSupabaseId) async {
  final db = AppDatabase.instance;
  final already = await (db.select(db.recipes)
        ..where((t) => t.supabaseId.like('$cocktailsImportIdPrefix%'))
        ..limit(1))
      .get();
  if (already.isNotEmpty) return;

  final raw = await rootBundle.loadString(cocktailsImportSeedAsset);
  final decoded = jsonDecode(raw) as Map<String, dynamic>;
  final list = (decoded['cocktails'] as List? ?? const [])
      .cast<Map<String, dynamic>>();
  if (list.isEmpty) return;

  final recipes = <Recipe>[];
  final ingredients = <RecipeIngredient>[];

  for (final item in list) {
    final id = item['supabaseId'] as String? ?? '';
    if (id.isEmpty) continue;

    final cuisine = ((item['cuisine'] as List?) ?? const [])
        .map((e) => e.toString())
        .where((s) => s.isNotEmpty)
        .toList();
    final flavors = ((item['flavorProfiles'] as List?) ?? const [])
        .map((e) => e.toString())
        .where((s) => s.isNotEmpty)
        .toList();

    final name = item['name'] as String? ?? '';
    final glassware = item['glassware'] as String?;
    recipes.add(
      Recipe()
        ..supabaseId = id
        ..boatSupabaseId = defaultBoatSupabaseId
        ..name = name
        ..description = item['description'] as String?
        ..instructions = item['instructions'] as String?
        ..recipeType = 'cocktail'
        ..isBundled = true
        ..isFavourite = isSeededFavouriteName(name)
        ..glassware = glassware
        ..prepMinutes = item['prepMinutes'] as int?
        ..story = item['story'] as String?
        ..cuisine = cuisine
        ..flavorProfiles = flavors
        ..imageAsset =
            cocktailImageAssetFor(name: name, glassware: glassware),
    );

    final rawIngs = (item['ingredients'] as List? ?? const []);
    for (var i = 0; i < rawIngs.length; i++) {
      final ing = rawIngs[i] as Map<String, dynamic>;
      final ingName = ing['name'] as String? ?? '';
      if (ingName.isEmpty) continue;
      final isGarnish = ing['isGarnish'] as bool? ?? false;
      final qtyRaw = ing['quantity'];
      double? qty;
      if (qtyRaw is num) qty = qtyRaw.toDouble();

      ingredients.add(
        RecipeIngredient()
          ..supabaseId =
              'ing_${id}_${ingName.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}_$i'
          ..recipeSupabaseId = id
          ..name = ingName
          ..quantity = isGarnish ? null : qty
          ..unit = isGarnish ? null : ing['unit'] as String?
          ..isGarnish = isGarnish
          ..garnishNotes = ing['garnishNotes'] as String?
          ..isOptional = ing['isOptional'] as bool? ?? false
          ..sortOrder = ing['sortOrder'] as int? ?? i,
      );
    }
  }

  await seedRecipesToDrift(recipes);
  await seedRecipeIngredientsToDrift(ingredients);
}
