import 'dart:convert';

import 'package:drift/drift.dart';
import 'package:flutter/services.dart' show rootBundle;

import '../../models/models.dart';
import '../drift/app_database.dart';
import 'recipe_drift_seed.dart';

/// Bundled Chef expansion pack from `lib/recipe_import.json`, processed for
/// 2-person base servings, complete ingredient lists, and pairing stories.
///
/// Regenerated by `tool/generate_menus_import_seed.py`.
const menusImportSeedAsset = 'assets/seed/menus_import_seed.json';

/// Prefix for every import-pack menu id (`menu_imp_…`).
const menusImportIdPrefix = 'menu_imp_';

/// Seeds the menus import expansion pack when it is not already present.
///
/// Safe on every startup: if any `menu_imp_*` recipe exists, this is a
/// **no-op** so user edits / favourites on those rows are preserved.
/// Fresh install / factory reset re-seeds via [seedRecipes].
Future<void> seedMenusImport(String defaultBoatSupabaseId) async {
  final db = AppDatabase.instance;
  final already = await (db.select(db.recipes)
        ..where((t) => t.supabaseId.like('$menusImportIdPrefix%'))
        ..limit(1))
      .get();
  if (already.isNotEmpty) return;

  final raw = await rootBundle.loadString(menusImportSeedAsset);
  final decoded = jsonDecode(raw) as Map<String, dynamic>;
  final list = (decoded['menus'] as List? ?? const [])
      .cast<Map<String, dynamic>>();
  if (list.isEmpty) return;

  final recipes = <Recipe>[];
  final ingredients = <RecipeIngredient>[];

  for (final item in list) {
    final id = item['supabaseId'] as String? ?? '';
    if (id.isEmpty) continue;

    final cuisine = ((item['cuisine'] as List?) ?? const [])
        .map((e) => e.toString())
        .where((s) => s.isNotEmpty)
        .toList();
    final flavors = ((item['flavorProfiles'] as List?) ?? const [])
        .map((e) => e.toString())
        .where((s) => s.isNotEmpty)
        .toList();

    recipes.add(
      Recipe()
        ..supabaseId = id
        ..boatSupabaseId = defaultBoatSupabaseId
        ..name = item['name'] as String? ?? ''
        ..description = item['description'] as String?
        ..instructions = item['instructions'] as String?
        ..recipeType = 'menu'
        ..isBundled = true
        ..cuisine = cuisine
        ..flavorProfiles = flavors
        ..cookingMethod = item['cookingMethod'] as String?
        ..prepMinutes = item['prepMinutes'] as int?
        ..cookMinutes = item['cookMinutes'] as int?
        ..story = item['story'] as String?,
    );

    final rawIngs = (item['ingredients'] as List? ?? const []);
    for (var i = 0; i < rawIngs.length; i++) {
      final ing = rawIngs[i] as Map<String, dynamic>;
      final name = ing['name'] as String? ?? '';
      if (name.isEmpty) continue;
      final isGarnish = ing['isGarnish'] as bool? ?? false;
      final qtyRaw = ing['quantity'];
      double? qty;
      if (qtyRaw is num) qty = qtyRaw.toDouble();

      ingredients.add(
        RecipeIngredient()
          ..supabaseId =
              'ing_${id}_${name.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]'), '_')}_$i'
          ..recipeSupabaseId = id
          ..name = name
          ..quantity = isGarnish ? null : qty
          ..unit = isGarnish ? null : ing['unit'] as String?
          ..substitute = ing['substitute'] as String?
          ..isGarnish = isGarnish
          ..isOptional = ing['isOptional'] as bool? ?? false
          ..sortOrder = i,
      );
    }
  }

  await seedRecipesToDrift(recipes);
  await seedRecipeIngredientsToDrift(ingredients);
}
