-- Consolidated baseline migration (squashed 2026-07-30).
--
-- Replaces 0001_sync_schema.sql .. 0009_checklist_groups_community_link.sql
-- (and several migrations applied directly to the live project with no
-- matching local file: harden_trigger_function_search_path,
-- boat_ownership_and_sharing, stale_warn_fix, stale_warn_add_column).
--
-- Generated by introspecting the live connected project directly (table
-- columns, RLS policies, functions, triggers, indexes, realtime publication
-- membership) rather than replaying the stale local files, per the
-- "no install base yet" policy in CLAUDE.md — schema history doesn't need to
-- preserve incremental back-compat migrations right now.
--
-- This file documents current reality; it is NOT re-executed against the
-- live project (which already has this exact schema) — only applied to a
-- fresh/local Supabase instance from here on.

-- ============================================================================
-- Tables
-- ============================================================================

create table public.boats (
  "supabaseId" text primary key,
  "id" text,
  "name" text,
  "isBought" boolean,
  "isHidden" boolean,
  "isSynced" boolean,
  "lastModified" timestamptz,
  "lastPurchasePrice" double precision,
  "notes" text,
  "origin" text,
  "photoUrl" text,
  "ownerId" uuid,
  "shareCode" text unique default upper(substr(replace((gen_random_uuid())::text, '-'::text, ''::text), 1, 6))
);

create table public.boat_members (
  "boatSupabaseId" text not null references public.boats("supabaseId"),
  "memberId" uuid not null,
  "role" text default 'crew'::text,
  "joinedAt" timestamptz default now(),
  primary key ("boatSupabaseId", "memberId")
);

create table public.profiles (
  "id" uuid primary key references auth.users(id),
  "boatGuid" text,
  "updatedAt" timestamptz default now(),
  "proUntil" timestamptz,
  "lastSeenAt" timestamptz,
  "warnedAt" timestamptz
);

create table public.app_admins (
  "id" uuid primary key references auth.users(id)
);

create table public.checklist_groups (
  "supabaseId" text primary key,
  "id" text,
  "boatSupabaseId" text,
  "appType" text,
  "title" text,
  "description" text,
  "iconName" text,
  "isBought" boolean,
  "isBundled" boolean,
  "isExpanded" boolean,
  "isHidden" boolean,
  "isSynced" boolean,
  "lastModified" timestamptz,
  "lastPurchasePrice" double precision,
  "notes" text,
  "origin" text,
  "sortOrder" integer,
  "communityTemplateId" text,
  "communityTemplateVersion" integer
);

create table public.checklist_items (
  "supabaseId" text primary key,
  "id" text,
  "boatSupabaseId" text,
  "groupSupabaseId" text,
  "title" text,
  "name" text,
  "description" text,
  "assetName" text,
  "photoUrl" text,
  "userPhotoUrl" text,
  "userPhotoPath" text,
  "notes" text,
  "isCompleted" boolean,
  "completedAt" timestamptz,
  "completionHistory" jsonb,
  "isBundled" boolean,
  "isHidden" boolean,
  "isPermanentlyDeleted" boolean,
  "isSynced" boolean,
  "createdAt" timestamptz,
  "lastModified" timestamptz,
  "sortOrder" integer
);

create table public.shopping_categories (
  "supabaseId" text primary key,
  "id" text,
  "boatSupabaseId" text,
  "name" text,
  "sortOrder" integer,
  "isSynced" boolean,
  "lastModified" timestamptz
);

create table public.shopping_items (
  "supabaseId" text primary key,
  "id" text,
  "boatSupabaseId" text,
  "categorySupabaseId" text,
  "name" text,
  "quantity" integer,
  "unit" text,
  "isBought" boolean,
  "isBundled" boolean,
  "isSynced" boolean,
  "isHidden" boolean,
  "notes" text,
  "origin" text,
  "lastPurchasePrice" double precision,
  "lastPurchasePlace" text,
  "userPhotoUrl" text,
  "lastModified" timestamptz
);

create table public.captain_logs (
  "supabaseId" text primary key,
  "id" text,
  "boatSupabaseId" text,
  "logDate" timestamptz,
  "title" text,
  "logTime" text,
  "positionLat" double precision,
  "positionLng" double precision,
  "weather" text,
  "windSpeedKt" integer,
  "windDir" text,
  "crewOnBoard" jsonb,
  "notes" text,
  "photos" jsonb,
  "isSynced" boolean,
  "lastModified" timestamptz
);

create table public.maintenance_tasks (
  "supabaseId" text primary key,
  "id" text,
  "boatSupabaseId" text,
  "description" text,
  "intervalHours" integer,
  "intervalMonths" integer,
  "lastDoneHours" integer,
  "lastDoneDate" timestamptz,
  "doneBy" text,
  "notes" text,
  "isHidden" boolean,
  "isSynced" boolean,
  "lastModified" timestamptz
);

create table public.documents (
  "supabaseId" text primary key,
  "id" text,
  "boatSupabaseId" text,
  "title" text,
  "type" text,
  "fileUrl" text,
  "localPath" text,
  "notes" text,
  "expiry" timestamptz,
  "isSynced" boolean,
  "lastModified" timestamptz
);

create table public.crew_members (
  "supabaseId" text primary key,
  "id" text,
  "boatSupabaseId" text,
  "name" text,
  "role" text,
  "phone" text,
  "email" text,
  "iceContact" text,
  "certifications" text,
  "localPath" text,
  "isSynced" boolean,
  "lastModified" timestamptz
);

create table public.inventory_items (
  "supabaseId" text primary key,
  "id" text,
  "boatSupabaseId" text,
  "name" text,
  "location" text,
  "quantity" double precision,
  "unit" text,
  "serialNumber" text,
  "notes" text,
  "localPath" text,
  "isSynced" boolean,
  "lastModified" timestamptz
);

create table public.fuel_logs (
  "supabaseId" text primary key,
  "id" text,
  "boatSupabaseId" text,
  "date" timestamptz,
  "type" text,
  "liters" double precision,
  "pricePerLiter" double precision,
  "totalCost" double precision,
  "notes" text,
  "isSynced" boolean,
  "lastModified" timestamptz
);

create table public.recipes (
  "supabaseId" text primary key,
  "id" text,
  "boatSupabaseId" text,
  "name" text,
  "description" text,
  "instructions" text,
  "recipeType" text,
  "createdAt" timestamptz,
  "isBundled" boolean,
  "isSynced" boolean,
  "missingIngredientCount" integer,
  "isFavourite" boolean,
  "glassware" text,
  "prepMinutes" integer,
  "cookMinutes" integer,
  "story" text,
  "tastingLog" jsonb,
  "cuisine" jsonb,
  "flavorProfiles" jsonb,
  "cookingMethod" text,
  "imageAsset" text,
  "localPath" text,
  "lastModified" timestamptz
);

create table public.recipe_ingredients (
  "supabaseId" text primary key,
  "id" text,
  "recipeSupabaseId" text,
  "name" text,
  "quantity" double precision,
  "unit" text,
  "substitute" text,
  "isGarnish" boolean,
  "garnishNotes" text,
  "isOptional" boolean,
  "photoUrl" text,
  "sortOrder" integer,
  "isSynced" boolean,
  "lastModified" timestamptz
);

create table public.bar_ingredients (
  "supabaseId" text primary key,
  "id" text,
  "name" text,
  "inMyBar" boolean,
  "sortOrder" integer,
  "isBundled" boolean,
  "isSynced" boolean,
  "category" text,
  "flavorProfiles" jsonb,
  "alcoholByVolume" double precision,
  "substitute1" text,
  "substitute2" text,
  "localPhotoPath" text,
  "imageUrl" text,
  "lastKnownPrice" double precision,
  "priceCurrency" text,
  "lastKnownPriceUnit" text,
  "lastPurchasePlace" text,
  "purchaseHistory" jsonb,
  "lastModified" timestamptz,
  "boatSupabaseId" text
);

create table public.pantry_ingredients (
  "supabaseId" text primary key,
  "id" text,
  "name" text,
  "inMyPantry" boolean,
  "quantity" double precision,
  "unit" text,
  "sortOrder" integer,
  "isBundled" boolean,
  "isSynced" boolean,
  "category" text,
  "flavorProfiles" jsonb,
  "cuisineTypes" jsonb,
  "allergenTags" jsonb,
  "dietaryTags" jsonb,
  "substitute1" text,
  "substitute2" text,
  "localPhotoPath" text,
  "imageUrl" text,
  "expiryDate" timestamptz,
  "lastKnownPrice" double precision,
  "priceCurrency" text,
  "lastKnownPriceUnit" text,
  "lastPurchasePlace" text,
  "purchaseHistory" jsonb,
  "caloriesPer100g" double precision,
  "proteinPer100g" double precision,
  "fatPer100g" double precision,
  "carbsPer100g" double precision,
  "lastModified" timestamptz,
  "boatSupabaseId" text
);

create table public.community_templates (
  "id" uuid primary key default gen_random_uuid(),
  "name" text default ''::text,
  "title" text default ''::text,
  "description" text default ''::text,
  "category" text default ''::text,
  "subcategory" text default ''::text,
  "author_id" text default ''::text,
  "content" text default ''::text,
  "is_approved" boolean default true,
  "last_modified" timestamptz default now(),
  "download_count" integer not null default 0,
  "avg_rating" numeric not null default 0,
  "rating_count" integer not null default 0,
  "version" integer not null default 1
);

create table public.community_downloads (
  "id" bigint generated always as identity primary key,
  "template_id" uuid references public.community_templates(id),
  "downloaded_at" timestamptz default now()
);

create table public.community_ratings (
  "id" bigint generated always as identity primary key,
  "template_id" uuid references public.community_templates(id),
  "user_id" text not null,
  "rating" smallint not null check (rating >= 1 and rating <= 5),
  "created_at" timestamptz default now(),
  "updated_at" timestamptz default now(),
  unique ("template_id", "user_id")
);

-- ============================================================================
-- Functions
-- ============================================================================

create or replace function public.sisu_set_id_from_supabase_id()
returns trigger
language plpgsql
set search_path to ''
as $function$
begin
  new."id" := new."supabaseId";
  return new;
end;
$function$;

create or replace function public.accessible_boat_ids()
returns setof text
language sql
stable security definer
set search_path to ''
as $function$
  select b."supabaseId" from public.boats b where b."ownerId" = auth.uid()
  union
  select bm."boatSupabaseId" from public.boat_members bm where bm."memberId" = auth.uid()
$function$;

create or replace function public.admin_check()
returns void
language plpgsql
security definer
set search_path to ''
as $function$
begin
  if not exists (select 1 from public.app_admins a where a."id" = auth.uid()) then
    raise exception 'Not authorized';
  end if;
end; $function$;

create or replace function public.admin_mark_warned(p_guid text)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare updated bigint;
begin
  perform public.admin_check();

  update public.profiles set "warnedAt" = now() where "boatGuid" = p_guid;
  get diagnostics updated = row_count;

  if updated = 0 then
    insert into public.profiles ("id", "boatGuid", "warnedAt")
    select b."ownerId", p_guid, now()
    from public.boats b
    where b."supabaseId" = p_guid and b."ownerId" is not null
    on conflict ("id") do update
      set "boatGuid" = excluded."boatGuid", "warnedAt" = excluded."warnedAt";
    get diagnostics updated = row_count;
  end if;

  return jsonb_build_object('boat', p_guid, 'profilesUpdated', updated);
end; $function$;

create or replace function public.admin_purge_boat(p_guid text)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare t text; n bigint; total bigint := 0;
begin
  perform public.admin_check();
  foreach t in array array[
    'checklist_groups','checklist_items','shopping_categories','shopping_items',
    'captain_logs','maintenance_tasks','documents','crew_members',
    'inventory_items','fuel_logs','recipes','recipe_ingredients',
    'bar_ingredients','pantry_ingredients'
  ] loop
    execute format('delete from public.%I where "supabaseId" like $1', t)
      using p_guid || '::%';
    get diagnostics n = row_count;
    total := total + n;
  end loop;
  delete from public.boat_members where "boatSupabaseId" = p_guid;
  delete from public.boats where "supabaseId" = p_guid;
  return jsonb_build_object('boat', p_guid, 'contentRowsDeleted', total);
end; $function$;

create or replace function public.admin_stale_boats(p_months integer default 12)
returns table("boatGuid" text, "boatName" text, "ownerEmail" text, "proUntil" timestamptz, "lastSeenAt" timestamptz, "warnedAt" timestamptz, "contentRows" bigint)
language plpgsql
security definer
set search_path to ''
as $function$
begin
  perform public.admin_check();
  return query
  select b."supabaseId", b."name", u.email::text, p."proUntil", p."lastSeenAt",
    p."warnedAt",
    (select count(*) from public.checklist_items ci
      where ci."supabaseId" like b."supabaseId" || '::%')
    + (select count(*) from public.captain_logs cl
      where cl."supabaseId" like b."supabaseId" || '::%')
    + (select count(*) from public.recipes r
      where r."supabaseId" like b."supabaseId" || '::%')
  from public.boats b
  left join public.profiles p on p."boatGuid" = b."supabaseId"
  left join auth.users u on u.id = p."id"
  where coalesce(p."proUntil", to_timestamp(0)) < now()
    and coalesce(p."lastSeenAt", to_timestamp(0)) < now() - make_interval(months => p_months);
end; $function$;

create or replace function public.admin_stats()
returns jsonb
language plpgsql
security definer
set search_path to ''
as $function$
declare result jsonb;
begin
  perform public.admin_check();
  select jsonb_build_object(
    'activeSubs', (select count(*) from public.profiles p where p."proUntil" > now()),
    'profiles', (select count(*) from public.profiles),
    'authUsers', (select count(*) from auth.users),
    'anonymousUsers', (select count(*) from auth.users where is_anonymous),
    'boats', (select count(*) from public.boats),
    'crewMemberships', (select count(*) from public.boat_members),
    'communityTemplates', (select count(*) from public.community_templates),
    'dbSizeMb', (select round(pg_database_size(current_database()) / 1048576.0, 1)),
    'rows', (
      select jsonb_object_agg(t.tbl, t.n) from (
        select 'checklist_items' as tbl, count(*) as n from public.checklist_items
        union all select 'checklist_groups', count(*) from public.checklist_groups
        union all select 'shopping_items', count(*) from public.shopping_items
        union all select 'captain_logs', count(*) from public.captain_logs
        union all select 'recipes', count(*) from public.recipes
        union all select 'bar_ingredients', count(*) from public.bar_ingredients
        union all select 'pantry_ingredients', count(*) from public.pantry_ingredients
        union all select 'documents', count(*) from public.documents
        union all select 'crew_members', count(*) from public.crew_members
        union all select 'inventory_items', count(*) from public.inventory_items
        union all select 'fuel_logs', count(*) from public.fuel_logs
      ) t)
  ) into result;
  return result;
end; $function$;

create or replace function public.increment_community_download_count()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  update public.community_templates
  set "download_count" = "download_count" + 1
  where "id" = new."template_id";
  return new;
end;
$function$;

create or replace function public.recompute_community_rating()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  target_id uuid;
begin
  target_id := coalesce(new.template_id, old.template_id);
  update public.community_templates t
  set
    "rating_count" = (
      select count(*) from public.community_ratings r
      where r."template_id" = target_id
    ),
    "avg_rating" = coalesce((
      select avg("rating")::numeric(3,2) from public.community_ratings r
      where r."template_id" = target_id
    ), 0)
  where t."id" = target_id;
  return null;
end;
$function$;

create or replace function public.redeem_boat_code(p_code text)
returns text
language plpgsql
security definer
set search_path to ''
as $function$
declare
  v_boat text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;
  select "supabaseId" into v_boat
    from public.boats
    where "shareCode" = upper(trim(p_code));
  if v_boat is null then
    raise exception 'Invalid boat code';
  end if;
  insert into public.boat_members ("boatSupabaseId", "memberId", "role")
    values (v_boat, auth.uid(), 'crew')
    on conflict ("boatSupabaseId", "memberId") do nothing;
  return v_boat;
end;
$function$;

create or replace function public.rls_auto_enable()
returns event_trigger
language plpgsql
security definer
set search_path to 'pg_catalog'
as $function$
declare
  cmd record;
begin
  for cmd in
    select *
    from pg_event_trigger_ddl_commands()
    where command_tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      and object_type in ('table','partitioned table')
  loop
     if cmd.schema_name is not null and cmd.schema_name in ('public') and cmd.schema_name not in ('pg_catalog','information_schema') and cmd.schema_name not like 'pg_toast%' and cmd.schema_name not like 'pg_temp%' then
      begin
        execute format('alter table if exists %s enable row level security', cmd.object_identity);
        raise log 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      exception
        when others then
          raise log 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      end;
     else
        raise log 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     end if;
  end loop;
end;
$function$;

-- ============================================================================
-- Triggers
-- ============================================================================

do $$
declare
  t text;
begin
  foreach t in array array[
    'boats','checklist_groups','checklist_items','shopping_categories',
    'shopping_items','captain_logs','maintenance_tasks','documents',
    'crew_members','inventory_items','fuel_logs','recipes',
    'recipe_ingredients','bar_ingredients','pantry_ingredients'
  ] loop
    execute format(
      'create trigger trg_%s_set_id before insert or update on public.%I for each row execute function public.sisu_set_id_from_supabase_id()',
      t, t
    );
  end loop;
end $$;

create trigger community_downloads_increment_count
  after insert on public.community_downloads
  for each row execute function public.increment_community_download_count();

create trigger community_ratings_recompute
  after insert or update or delete on public.community_ratings
  for each row execute function public.recompute_community_rating();

create event trigger ensure_rls
  on ddl_command_end
  execute function public.rls_auto_enable();

-- ============================================================================
-- Row Level Security
-- ============================================================================

alter table public.boats enable row level security;
alter table public.boat_members enable row level security;
alter table public.profiles enable row level security;
alter table public.app_admins enable row level security;
alter table public.checklist_groups enable row level security;
alter table public.checklist_items enable row level security;
alter table public.shopping_categories enable row level security;
alter table public.shopping_items enable row level security;
alter table public.captain_logs enable row level security;
alter table public.maintenance_tasks enable row level security;
alter table public.documents enable row level security;
alter table public.crew_members enable row level security;
alter table public.inventory_items enable row level security;
alter table public.fuel_logs enable row level security;
alter table public.recipes enable row level security;
alter table public.recipe_ingredients enable row level security;
alter table public.bar_ingredients enable row level security;
alter table public.pantry_ingredients enable row level security;
alter table public.community_templates enable row level security;
alter table public.community_downloads enable row level security;
alter table public.community_ratings enable row level security;

create policy boats_select on public.boats for select to authenticated
  using ("supabaseId" in (select accessible_boat_ids()));
create policy boats_insert on public.boats for insert to authenticated
  with check ("ownerId" = auth.uid());
create policy boats_update on public.boats for update to authenticated
  using ("ownerId" = auth.uid()) with check ("ownerId" = auth.uid());
create policy boats_delete on public.boats for delete to authenticated
  using ("ownerId" = auth.uid());

create policy member_reads_own on public.boat_members for select
  using ("memberId" = auth.uid() or exists (
    select 1 from public.boats b
    where b."supabaseId" = boat_members."boatSupabaseId" and b."ownerId" = auth.uid()
  ));
create policy owner_deletes_members on public.boat_members for delete
  using (exists (
    select 1 from public.boats b
    where b."supabaseId" = boat_members."boatSupabaseId" and b."ownerId" = auth.uid()
  ));

create policy profiles_own on public.profiles for all to authenticated
  using ("id" = auth.uid()) with check ("id" = auth.uid());

do $$
declare
  t text;
begin
  foreach t in array array[
    'checklist_groups','checklist_items','shopping_categories','shopping_items',
    'captain_logs','maintenance_tasks','documents','crew_members',
    'inventory_items','fuel_logs','recipes','recipe_ingredients',
    'bar_ingredients','pantry_ingredients'
  ] loop
    execute format(
      $p$create policy sisu_boat_scoped on public.%I for all to authenticated
        using (split_part("supabaseId", '::', 1) in (select accessible_boat_ids()))
        with check (split_part("supabaseId", '::', 1) in (select accessible_boat_ids()))$p$,
      t
    );
  end loop;
end $$;

create policy community_read on public.community_templates for select to authenticated
  using (is_approved = true or author_id = (auth.uid())::text);
create policy community_publish on public.community_templates for insert to authenticated
  with check (author_id = (auth.uid())::text and coalesce(((auth.jwt() ->> 'is_anonymous'::text))::boolean, false) = false);
create policy community_author_update on public.community_templates for update to authenticated
  using (author_id = (auth.uid())::text) with check (author_id = (auth.uid())::text);
create policy community_author_delete on public.community_templates for delete to authenticated
  using (author_id = (auth.uid())::text);

create policy downloads_read on public.community_downloads for select to authenticated
  using (true);
create policy downloads_insert on public.community_downloads for insert to authenticated
  with check (true);

create policy ratings_read on public.community_ratings for select to authenticated
  using (true);
create policy ratings_upsert_own on public.community_ratings for insert to authenticated
  with check (user_id = (auth.uid())::text and coalesce(((auth.jwt() ->> 'is_anonymous'::text))::boolean, false) = false);
create policy ratings_update_own on public.community_ratings for update to authenticated
  using (user_id = (auth.uid())::text) with check (user_id = (auth.uid())::text);
create policy ratings_delete_own on public.community_ratings for delete to authenticated
  using (user_id = (auth.uid())::text);

-- ============================================================================
-- Realtime publication
-- ============================================================================

alter publication supabase_realtime add table public.boats;
alter publication supabase_realtime add table public.checklist_groups;
alter publication supabase_realtime add table public.checklist_items;
alter publication supabase_realtime add table public.shopping_categories;
alter publication supabase_realtime add table public.shopping_items;
alter publication supabase_realtime add table public.captain_logs;
alter publication supabase_realtime add table public.maintenance_tasks;
alter publication supabase_realtime add table public.documents;
alter publication supabase_realtime add table public.crew_members;
alter publication supabase_realtime add table public.inventory_items;
alter publication supabase_realtime add table public.fuel_logs;
alter publication supabase_realtime add table public.recipes;
alter publication supabase_realtime add table public.recipe_ingredients;
alter publication supabase_realtime add table public.bar_ingredients;
alter publication supabase_realtime add table public.pantry_ingredients;
